main:
  - name: About
    URL: about
    weight: 1
  - name: Post
    URL: blog
    weight: 2
  - name: Contact
    URL: contact
    weight: 3
footer:
  - name: About
    URL: about
    weight: 1
  - name: Post
    URL: blog
    weight: 2
  - name: Contact
    URL: contact
    weight: 3